services:
  db:
    image: postgres:15
    container_name: postgres-reservas
    restart: always
    environment:
      POSTGRES_USER: pauloaabrantes
      POSTGRES_PASSWORD: p1a2u3l4o5..docker
      POSTGRES_DB: reserva_quadras
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
