services:
  db:
    image: postgres:15
    container_name: postgres-backclub
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: backclub_db
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
